services:
  result:
    build:
      context: result
      dockerfile: Dockerfile
    ports:
      - "8180:80"
    env_file:
      - .env
    networks:
      - "voting-app"
  vote:
    build:
      context: vote
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    env_file:
      - .env
    networks:
      - "voting-app"
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - "voting-app"
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - "voting-app"
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - "voting-app"

networks:
  voting-app:

